/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.ItensDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ObjItens;

/**
 *
 * @author 181710018
 */
public class Operacoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Operações
     */
    
    private JDesktopPane painelTelaInicial;
    public List<ObjItens> listaItens;
    
    public Operacoes(JDesktopPane painelTelaInicial) {
        initComponents();
        this.painelTelaInicial = painelTelaInicial;
        listaItens = new ArrayList<>();
        carregarTabela();
        Color minhaCor = new Color(174, 174, 174);
        getContentPane().setBackground(minhaCor);
    }
    
    public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel();
        String[] colunas = { "Nome", "Quantidade"};
        modelo.setColumnIdentifiers(colunas);
        for(ObjItens ite : listaItens){
            Object[] obj = { 
                ite.getNome(), 
                ite.getQuantidade()
            };
            modelo.addRow(obj);
        }
        tableItens.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAdd = new javax.swing.JButton();
        BtnExc = new javax.swing.JButton();
        BtnFim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItens = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Operações");

        BtnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAdd.setText("Adicionar Item");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnExc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnExc.setText("Excluir Item");
        BtnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcActionPerformed(evt);
            }
        });

        BtnFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnFim.setText("Finalizar Operação");
        BtnFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFimActionPerformed(evt);
            }
        });

        tableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableItens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnExc))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(BtnFim)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd)
                    .addComponent(BtnExc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnFim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        SelectItens tela = new SelectItens(this);
        this.painelTelaInicial.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcActionPerformed
        int linha = tableItens.getSelectedRow();
        if(linha == -1){
            JOptionPane.showMessageDialog(this, "Você deve selecionar um item para retirar da tabela!");
        }else{
            int resposta = JOptionPane.showConfirmDialog(this,
                    "Confirma a exclusão do Item? " ,
                    "Excluir Item", 
                    JOptionPane.YES_NO_OPTION);
            if( resposta == JOptionPane.YES_OPTION ){
                listaItens.remove(linha);
                carregarTabela();
            }
        }
    }//GEN-LAST:event_BtnExcActionPerformed

    private void BtnFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFimActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this,
                    "Confirma o uso do Item? " ,
                    "Terminar Operação", 
                    JOptionPane.YES_NO_OPTION);
            if( resposta == JOptionPane.YES_OPTION )
                for(ObjItens ite : listaItens){
                Object[] obj = { 
                    ite.getCodigo(), 
                    ite.getQuantidade()
                };
                ItensDAO.atualizar(ite);
            }
            listaItens.removeAll(listaItens);
            carregarTabela();
    }//GEN-LAST:event_BtnFimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnExc;
    private javax.swing.JButton BtnFim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItens;
    // End of variables declaration//GEN-END:variables
}
