/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author 181710018
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelaInicial = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuIniciar = new javax.swing.JMenu();
        MenuAbrirOp = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuFornecedores = new javax.swing.JMenu();
        MenuCadastrarFornecedores = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuContatoFornecedores = new javax.swing.JMenuItem();
        MenuItens = new javax.swing.JMenu();
        MenuCadastrarItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuEstoqueItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínicas");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jdpTelaInicial.setBackground(new java.awt.Color(0, 153, 204));
        jdpTelaInicial.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jdpTelaInicial.setForeground(new java.awt.Color(102, 102, 102));
        jdpTelaInicial.setToolTipText("");
        jdpTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdpTelaInicial.setDesktopManager(null);
        jdpTelaInicial.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/Clínica-Médica.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/logo.png"))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Criado por invoked");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/imgBemVindo.png"))); // NOI18N

        jdpTelaInicial.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpTelaInicial.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpTelaInicial.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpTelaInicial.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpTelaInicialLayout = new javax.swing.GroupLayout(jdpTelaInicial);
        jdpTelaInicial.setLayout(jdpTelaInicialLayout);
        jdpTelaInicialLayout.setHorizontalGroup(
            jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpTelaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jdpTelaInicialLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jdpTelaInicialLayout.setVerticalGroup(
            jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpTelaInicialLayout.createSequentialGroup()
                .addGroup(jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdpTelaInicialLayout.createSequentialGroup()
                        .addGroup(jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdpTelaInicialLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdpTelaInicialLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(255, 51, 51));

        MenuIniciar.setText("Iniciar");

        MenuAbrirOp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        MenuAbrirOp.setText("Abrir Operações");
        MenuAbrirOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbrirOpActionPerformed(evt);
            }
        });
        MenuIniciar.add(MenuAbrirOp);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Imprimir");
        MenuIniciar.add(jMenuItem1);
        MenuIniciar.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Sair");
        MenuIniciar.add(jMenuItem2);

        jMenuBar1.add(MenuIniciar);

        MenuFornecedores.setText("Fornecedores");

        MenuCadastrarFornecedores.setText("Cadastrar");
        MenuCadastrarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarFornecedoresActionPerformed(evt);
            }
        });
        MenuFornecedores.add(MenuCadastrarFornecedores);
        MenuFornecedores.add(jSeparator2);

        MenuContatoFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuContatoFornecedores.setText("Lista e Contato");
        MenuContatoFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContatoFornecedoresActionPerformed(evt);
            }
        });
        MenuFornecedores.add(MenuContatoFornecedores);

        jMenuBar1.add(MenuFornecedores);

        MenuItens.setText("Utensílios Clínicos");

        MenuCadastrarItem.setText("Novo Item");
        MenuCadastrarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarItemActionPerformed(evt);
            }
        });
        MenuItens.add(MenuCadastrarItem);
        MenuItens.add(jSeparator3);

        MenuEstoqueItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuEstoqueItem.setText("Estoque");
        MenuEstoqueItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEstoqueItemActionPerformed(evt);
            }
        });
        MenuItens.add(MenuEstoqueItem);

        jMenuBar1.add(MenuItens);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaInicial, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaInicial)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastrarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarFornecedoresActionPerformed
        FrmFornecedores frm = new FrmFornecedores();
        jdpTelaInicial.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MenuCadastrarFornecedoresActionPerformed

    private void MenuCadastrarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarItemActionPerformed
        FrmItens frm = new FrmItens();
        jdpTelaInicial.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_MenuCadastrarItemActionPerformed

    private void MenuContatoFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContatoFornecedoresActionPerformed
        ListFornecedores list = new ListFornecedores(jdpTelaInicial);
        jdpTelaInicial.add(list);
        list.setVisible(true);
    }//GEN-LAST:event_MenuContatoFornecedoresActionPerformed

    private void MenuEstoqueItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEstoqueItemActionPerformed
        ListItens list = new ListItens(jdpTelaInicial);
        jdpTelaInicial.add(list);
        list.setVisible(true);
    }//GEN-LAST:event_MenuEstoqueItemActionPerformed

    private void MenuAbrirOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbrirOpActionPerformed
        Operacoes op = new Operacoes(jdpTelaInicial);
        jdpTelaInicial.add(op);
        op.setVisible(true);
    }//GEN-LAST:event_MenuAbrirOpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAbrirOp;
    private javax.swing.JMenuItem MenuCadastrarFornecedores;
    private javax.swing.JMenuItem MenuCadastrarItem;
    private javax.swing.JMenuItem MenuContatoFornecedores;
    private javax.swing.JMenuItem MenuEstoqueItem;
    private javax.swing.JMenu MenuFornecedores;
    private javax.swing.JMenu MenuIniciar;
    private javax.swing.JMenu MenuItens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JDesktopPane jdpTelaInicial;
    // End of variables declaration//GEN-END:variables
}
